[[redirects]]
  from = "/docs/auth/*"
  to = "/docs/components/auth/:splat"
  status = 301

[[redirects]]
  from = "/docs/data-display/*"
  to = "/docs/components/data-display/:splat"
  status = 301


[[redirects]]
  from = "/docs/engagement/*"
  to = "/docs/components/engagement/:splat"
  status = 301

[[redirects]]
  from = "/docs/feedback/*"
  to = "/docs/components/feedback/:splat"
  status = 301

[[redirects]]
  from = "/docs/forms/*"
  to = "/docs/components/forms/:splat"
  status = 301

[[redirects]]
  from = "/docs/layout/*"
  to = "/docs/components/layout/:splat"
  status = 301

[[redirects]]
  from = "/docs/navigation/*"
  to = "/docs/components/navigation/:splat"
  status = 301

[[redirects]]
  from = "/docs/overlay/*"
  to = "/docs/components/overlay/:splat"
  status = 301

[[redirects]]
  from = "/docs/typography/*"
  to = "/docs/components/typography/:splat"
  status = 301

[[redirects]]
  from = "/docs/utils/*"
  to = "/docs/components/utils/:splat"
  status = 301

[[redirects]]
  from = "/docs/web3/*"
  to = "/docs/components/web3/:splat"
  status = 301

[[redirects]]
  from = "/docs/getting-started/*"
  to = "/docs/core/getting-started/:splat"
  status = 301

[[redirects]]
  from = "/docs/getting-started/*"
  to = "/docs/core/getting-started/:splat"
  status = 301

[[redirects]]
  from = "/docs/installation/*"
  to = "/docs/core/installation/:splat"
  status = 301

  
[[redirects]]
  from = "/docs/theming/*"
  to = "/docs/core/theming/:splat"
  status = 301

  